/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomePage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LandingPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ListCreation`; params?: Router.UnknownInputParams; } | { pathname: `/screens/PickList`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ResetPassword`; params?: Router.UnknownInputParams; } | { pathname: `/screens/TestLandingPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/VerifySecurityAnswer`; params?: Router.UnknownInputParams; } | { pathname: `/screens/VocabListPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/createAccount`; params?: Router.UnknownInputParams; } | { pathname: `/screens/login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/wordList`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ForgotPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/HomePage`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/LandingPage`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ListCreation`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/PickList`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ResetPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/TestLandingPage`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/VerifySecurityAnswer`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/VocabListPage`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/createAccount`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/login`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/wordList`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screens/ForgotPassword${`?${string}` | `#${string}` | ''}` | `/screens/HomePage${`?${string}` | `#${string}` | ''}` | `/screens/LandingPage${`?${string}` | `#${string}` | ''}` | `/screens/ListCreation${`?${string}` | `#${string}` | ''}` | `/screens/PickList${`?${string}` | `#${string}` | ''}` | `/screens/ResetPassword${`?${string}` | `#${string}` | ''}` | `/screens/TestLandingPage${`?${string}` | `#${string}` | ''}` | `/screens/VerifySecurityAnswer${`?${string}` | `#${string}` | ''}` | `/screens/VocabListPage${`?${string}` | `#${string}` | ''}` | `/screens/createAccount${`?${string}` | `#${string}` | ''}` | `/screens/login${`?${string}` | `#${string}` | ''}` | `/screens/wordList${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomePage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LandingPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ListCreation`; params?: Router.UnknownInputParams; } | { pathname: `/screens/PickList`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ResetPassword`; params?: Router.UnknownInputParams; } | { pathname: `/screens/TestLandingPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/VerifySecurityAnswer`; params?: Router.UnknownInputParams; } | { pathname: `/screens/VocabListPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/createAccount`; params?: Router.UnknownInputParams; } | { pathname: `/screens/login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/wordList`; params?: Router.UnknownInputParams; };
    }
  }
}
